name: network
description: >
  Library Contain method which will connect with backend:
    Get, Post, Update, Auth, Delete.
  Call Before Use Package: 
    1st Call Network configuration, 2nd Call Network Base.
  Exception: 
    Used when Error happen Exception will throw.
  Dependency:
    On DIO package.


version: 1.0.0
repository: https://github.com/jokerMabrouk/network-futter-dart.git

environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  dio: ^5.1.1
